# Generated by Django 5.0.2 on 2024-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mnumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
