# Generated by Django 5.0.2 on 2024-03-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='ContactlistModel',
        ),
    ]
