# Generated by Django 5.0.2 on 2024-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimage', models.ImageField(upload_to='static/uploads/')),
                ('mdis', models.TextField()),
            ],
        ),
    ]
