# Generated by Django 5.0.2 on 2024-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_missionmodel_mtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='visionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtitle', models.CharField(max_length=200)),
                ('vimage', models.ImageField(upload_to='static/uploads/')),
                ('vdis', models.TextField()),
            ],
        ),
    ]
