# Generated by Django 5.0.2 on 2024-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_visionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesModdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valimage', models.ImageField(upload_to='static/uploads/')),
                ('valtitle', models.CharField(max_length=100)),
                ('valdetails', models.TextField()),
            ],
        ),
    ]
