# Generated by Django 5.0.2 on 2024-03-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_visioncardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('himage', models.ImageField(upload_to='static/uploads/')),
                ('hdate', models.CharField(max_length=100)),
                ('hdetails', models.TextField()),
            ],
        ),
    ]
