# Generated by Django 5.0.2 on 2024-03-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_gallerys1model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerys2model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s2img', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
    ]
