# Generated by Django 5.0.2 on 2024-03-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_gallerys2model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerys3model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3img', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
    ]
