# Generated by Django 5.0.2 on 2024-03-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0010_gallerys3model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerys4model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s4vid', models.FileField(upload_to='static/uploads/')),
                ('s4edis', models.TextField()),
                ('s4mdis', models.TextField()),
            ],
        ),
    ]
