# Generated by Django 5.0.2 on 2024-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0012_activityslidermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiname', models.CharField(max_length=100)),
                ('actiimage', models.ImageField(upload_to='static/uploads/')),
                ('actititle', models.CharField(max_length=100)),
            ],
        ),
    ]
