# Generated by Django 5.0.2 on 2024-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_activitymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivdate', models.CharField(max_length=100)),
                ('achivtitle', models.CharField(max_length=100)),
                ('achivdis', models.CharField(max_length=300)),
            ],
        ),
    ]
