# Generated by Django 5.0.2 on 2024-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0015_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=200)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs_image', models.ImageField(upload_to='static/uploads/')),
                ('blogs_title', models.CharField(max_length=200)),
                ('blogs_description', models.CharField(max_length=200)),
                ('blogs_text', models.CharField(max_length=200)),
                ('blogs_head', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CertifideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifide_image', models.ImageField(upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_image', models.ImageField(upload_to='static/upolads/')),
                ('services_title', models.CharField(max_length=200)),
                ('services_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='static/uploads/')),
                ('slider_title', models.CharField(max_length=200)),
                ('slider_description', models.CharField(max_length=200)),
            ],
        ),
    ]
