# Generated by Django 5.0.2 on 2024-03-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0016_adminmodel_blogsmodel_certifidemodel_servicesmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionmodel',
            name='vdis',
        ),
    ]
