# Generated by Django 5.0.2 on 2024-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0017_remove_visionmodel_vdis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RhistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhimage', models.ImageField(upload_to='static/uploads/')),
                ('rhdate', models.CharField(max_length=100)),
                ('rhdetails', models.TextField()),
            ],
        ),
    ]
