# Generated by Django 5.0.2 on 2024-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0018_rhistorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivimage', models.ImageField(upload_to='static/uploads/')),
                ('achivdate', models.CharField(max_length=200)),
                ('achivtitle', models.CharField(max_length=200)),
                ('achivdis', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='achievementmodel',
            name='achivdate',
        ),
        migrations.AddField(
            model_name='achievementmodel',
            name='achivimage',
            field=models.ImageField(default=1, upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
