# Generated by Django 5.0.2 on 2024-03-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0019_achievementmodel2_remove_achievementmodel_achivdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdesign',
            name='mimage2',
            field=models.ImageField(default=1, upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
