# Generated by Django 5.0.2 on 2024-03-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0021_mdesign2_remove_mdesign_mimage2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitymodel',
            name='actiname',
        ),
    ]
